analysisCoverage: full
java:
  assessmentDomains:
  - java-upgrade
  - cloud-readiness
  targetRuntime: openjdk25
  targetComputeServices:
  - azure-aks
  targetOS:
  - linux
  - windows
dotnet:
  assessmentDomains:
  - dotnet-upgrade
  - cloud-readiness
  targetRuntime: net10.0
  targetComputeServices:
  - Any